services:
  postgres_pgvector:
    image: pgvector/pgvector:pg16
    container_name: media_rag_pgvector
    restart: unless-stopped
    environment:
      POSTGRES_USER: media
      POSTGRES_PASSWORD: media
      POSTGRES_DB: media_rag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql:rw
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready -U media"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: media_rag_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console Web
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    restart: unless-stopped


  upload.api:
    image: ${DOCKER_REGISTRY-}uploadapi
    build:
      context: .
      dockerfile: src/services/Upload.Api/Dockerfile
    depends_on:
      postgres_pgvector:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_pgvector;Port=5432;Database=media_rag;Username=media;Password=media
      - RabbitMq__HostName=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

    


  query.api:
    image: ${DOCKER_REGISTRY-}queryapi
    build:
      context: .
      dockerfile: src/services/Query.Api/Dockerfile
    depends_on:
      postgres_pgvector:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "5002:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_pgvector;Port=5432;Database=media_rag;Username=media;Password=media
      - Ollama__BaseUrl=http://host.docker.internal:11434
      - Embedding__BaseUrl=http://host.docker.internal:11434
      - Embedding__Model=bge-m3
      - Chat__Model=phi3:mini
      - Chat__BaseUrl=http://host.docker.internal:11434
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080


  mediatranscription.worker:
    image: ${DOCKER_REGISTRY-}mediatranscriptionworker
    build:
      context: .
      dockerfile: src/services/Transcription.Worker/Dockerfile
    depends_on:
      postgres_pgvector:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_pgvector;Port=5432;Database=media_rag;Username=media;Password=media
      - RabbitMq__HostName=rabbitmq

  mediaembedding.worker:
    image: ${DOCKER_REGISTRY-}mediaembeddingworker
    build:
      context: .
      dockerfile: src/services/Embedding.Worker/Dockerfile
    depends_on:
      postgres_pgvector:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_pgvector;Port=5432;Database=media_rag;Username=media;Password=media
      - RabbitMq__HostName=rabbitmq
      - Embedding__BaseUrl=http://host.docker.internal:11434
      - Embedding__Model=bge-m3
      - Ollama__BaseUrl=http://host.docker.internal:11434

volumes:
  postgres_data:
  rabbitmq_data:
  minio_data: